#!/bin/bash

cd $HOME/
mkdir CFDEM
cd CFDEM
git clone git://github.com/CFDEMproject/CFDEMcoupling-PUBLIC.git
cd $HOME/CFDEM/
mkdir LIGGGHTS
cd LIGGGHTS
git clone git://github.com/CFDEMproject/LIGGGHTS-PUBLIC.git
git clone git://github.com/CFDEMproject/LPP.git lpp

cd $HOME
mkdir OpenFOAM
cd OpenFOAM

git clone git://github.com/OpenFOAM/OpenFOAM-5.x.git
git clone git://github.com/OpenFOAM/ThirdParty-5.x.git
cd OpenFOAM-5.x
git checkout 538044ac05c4672b37c7df607dca1116fa88df88


cp $HOME/data/CFDEM/.bashrc/ ~/.bashrc
source ~/.bashrc
cd $WM_PROJECT_DIR
./Allwmake

cd $HOME/CFDEM/CFDEM
mv CFDEMcoupling-PUBLIC CFDEMcoupling-PUBLIC-$WM_PROJECT_VERSION

cfdemCompCFDEMall
